#!/usr/bin/env python3
"""
Compare purchase (compras) totals between:
- Accountant spreadsheet (.xls) like "IVA apur. 3º trim.xls" (sheet: "IVA 3 TRIM")
- IVAzen export (.xlsx) generated by dpExcelGenerator (sheet: "Resumo DP")

Focus: Campos 20-24 (IVA dedutivel) + optional Campo 91 (total dedutivel + ajustes).
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from typing import Optional

import pandas as pd


FIELDS_PURCHASES = [20, 21, 22, 23, 24]
FIELDS_EXTRA = [91]

# VAT rate cells that appear between Campo N and its value in some spreadsheets.
_VAT_RATE_VALUES = {0.06, 0.13, 0.23}


@dataclass(frozen=True)
class FieldValue:
    field: int
    value: float
    row: int


def _is_num(x) -> bool:
    return isinstance(x, (int, float)) and not pd.isna(x)


def extract_field_value(df: pd.DataFrame, field: int) -> Optional[FieldValue]:
    # Find first row containing the field number (usually stored as float in Excel).
    #
    # Important: Some sheets place multiple "Campo" numbers on the same row (e.g. 91 and 92),
    # so we can't just pick the rightmost number in the row. Instead, find the cell that
    # contains the field and then pick the next numeric cell to the right.
    for r in range(len(df)):
        row = df.iloc[r].tolist()
        for c, v in enumerate(row):
            if not (_is_num(v) and int(v) == field and abs(float(v) - field) < 1e-6):
                continue

            for c2 in range(c + 1, len(row)):
                v2 = row[c2]
                if not _is_num(v2):
                    continue
                # Some accountant templates include the VAT rate as the next numeric cell (e.g. 21 | 0.06 | 0.00).
                if any(abs(float(v2) - r) < 1e-6 for r in _VAT_RATE_VALUES):
                    continue
                # Skip if we stumbled into another field number cell.
                if abs(float(v2) - int(v2)) < 1e-6:
                    maybe_field = int(v2)
                    if maybe_field == field:
                        continue
                return FieldValue(field=field, value=float(v2), row=r)
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--accountant-xls", required=True, help="Path to accountant .xls (sheet: 'IVA 3 TRIM')")
    ap.add_argument("--ivazen-xlsx", required=True, help="Path to IVAzen export .xlsx (sheet: 'Resumo DP')")
    args = ap.parse_args()

    acc_df = pd.read_excel(args.accountant_xls, sheet_name="IVA 3 TRIM", header=None)
    sys_df = pd.read_excel(args.ivazen_xlsx, sheet_name="Resumo DP", header=None)

    def collect(df: pd.DataFrame, fields: list[int]) -> dict[int, FieldValue]:
        out: dict[int, FieldValue] = {}
        for f in fields:
            fv = extract_field_value(df, f)
            if fv is None:
                raise SystemExit(f"Could not find Campo {f} in sheet")
            out[f] = fv
        return out

    acc = collect(acc_df, FIELDS_PURCHASES + FIELDS_EXTRA)
    sys = collect(sys_df, FIELDS_PURCHASES + FIELDS_EXTRA)

    print("Compras (IVA dedutivel) - comparacao por campo")
    print("Campo | Contabilidade | IVAzen | Delta")
    print("----- | ------------- | ------ | -----")
    for f in FIELDS_PURCHASES + FIELDS_EXTRA:
        a = acc[f].value
        s = sys[f].value
        print(f"{f:>5} | {a:>13.2f} | {s:>6.2f} | {(s-a):>+.2f}")

    acc_total = sum(acc[f].value for f in FIELDS_PURCHASES)
    sys_total = sum(sys[f].value for f in FIELDS_PURCHASES)
    print()
    print(f"Soma Campos 20-24 | Contabilidade {acc_total:.2f} | IVAzen {sys_total:.2f} | Delta {(sys_total-acc_total):+.2f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
