// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const TEST_SUPABASE_URL = 'https://example.supabase.co';
const TEST_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_test_key';

const isTestEnv = import.meta.env.MODE === 'test' || Boolean((import.meta.env as any).VITEST);

// Minimal in-memory storage for tests (avoids auth auto-refresh timers and localStorage issues in jsdom).
const memoryStorage = (() => {
  const store = new Map<string, string>();
  return {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => { store.set(key, value); },
    removeItem: (key: string) => { store.delete(key); },
  } as any;
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export function resolveSupabaseRuntimeConfig(params: {
  url?: string;
  publishableKey?: string;
  isTestEnv: boolean;
}) {
  return {
    url: params.isTestEnv ? (params.url || TEST_SUPABASE_URL) : params.url,
    publishableKey: params.isTestEnv
      ? (params.publishableKey || TEST_SUPABASE_PUBLISHABLE_KEY)
      : params.publishableKey,
  };
}

const supabaseConfig = resolveSupabaseRuntimeConfig({
  url: SUPABASE_URL,
  publishableKey: SUPABASE_PUBLISHABLE_KEY,
  isTestEnv,
});

export const supabase = createClient<Database>(supabaseConfig.url, supabaseConfig.publishableKey, {
  auth: {
    storage: (!isTestEnv && typeof localStorage !== 'undefined') ? localStorage : memoryStorage,
    persistSession: !isTestEnv,
    autoRefreshToken: !isTestEnv,
  }
});
