-- B5: Reativar Constraints (executar DEPOIS de importar todos os CSVs)
SET session_replication_role = 'origin';
ALTER TABLE public.profiles ENABLE TRIGGER ALL;
ALTER TABLE public.user_roles ENABLE TRIGGER ALL;
ALTER TABLE public.invoices ENABLE TRIGGER ALL;
ALTER TABLE public.invoice_vat_lines ENABLE TRIGGER ALL;
ALTER TABLE public.invoice_validation_logs ENABLE TRIGGER ALL;
ALTER TABLE public.tax_withholdings ENABLE TRIGGER ALL;
ALTER TABLE public.withholding_logs ENABLE TRIGGER ALL;
ALTER TABLE public.at_withholding_candidates ENABLE TRIGGER ALL;
ALTER TABLE public.sales_invoices ENABLE TRIGGER ALL;
ALTER TABLE public.revenue_entries ENABLE TRIGGER ALL;
ALTER TABLE public.ss_declarations ENABLE TRIGGER ALL;
ALTER TABLE public.at_credentials ENABLE TRIGGER ALL;
ALTER TABLE public.accountant_at_config ENABLE TRIGGER ALL;
ALTER TABLE public.accountant_requests ENABLE TRIGGER ALL;
ALTER TABLE public.client_accountants ENABLE TRIGGER ALL;
ALTER TABLE public.client_invitations ENABLE TRIGGER ALL;
ALTER TABLE public.category_preferences ENABLE TRIGGER ALL;
ALTER TABLE public.classification_rules ENABLE TRIGGER ALL;
ALTER TABLE public.classification_examples ENABLE TRIGGER ALL;
ALTER TABLE public.notification_preferences ENABLE TRIGGER ALL;
ALTER TABLE public.push_subscriptions ENABLE TRIGGER ALL;
ALTER TABLE public.sent_notifications ENABLE TRIGGER ALL;
ALTER TABLE public.user_onboarding_progress ENABLE TRIGGER ALL;
ALTER TABLE public.upload_queue ENABLE TRIGGER ALL;
ALTER TABLE public.at_sync_history ENABLE TRIGGER ALL;
ALTER TABLE public.at_sync_jobs ENABLE TRIGGER ALL;
ALTER TABLE public.at_sync_year_overrides ENABLE TRIGGER ALL;
ALTER TABLE public.at_sync_override_audit ENABLE TRIGGER ALL;
ALTER TABLE public.at_sync_automation_runs ENABLE TRIGGER ALL;
ALTER TABLE public.partners ENABLE TRIGGER ALL;
ALTER TABLE public.ai_metrics ENABLE TRIGGER ALL;
SELECT 'PRONTO — Constraints reativadas!' AS status;